version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
  alpr:
    build: ./openalpr
    user: root
    volumes:
      - ./public/alprd_images:/var/lib/openalpr/plateimages      
volumes:
 dbdata: